class JuzModel {
  final int number;
  final String name;
  final int startSurahNum;
  final String startSurahName;
  final int startAyah;
  final int endSurahNum;
  final String endSurahName;
  final int endAyah;
  final int versesCount;

  const JuzModel({
    required this.number,
    required this.name,
    required this.startSurahNum,
    required this.startSurahName,
    required this.startAyah,
    required this.endSurahNum,
    required this.endSurahName,
    required this.endAyah,
    required this.versesCount,
  });

  static const List<JuzModel> allJuzs = [
    JuzModel(
      number: 1,
      name: 'الم',
      startSurahNum: 1,
      startSurahName: 'الفاتحة',
      startAyah: 1,
      endSurahNum: 2,
      endSurahName: 'البقرة',
      endAyah: 141,
      versesCount: 148,
    ),
    JuzModel(
      number: 2,
      name: 'سيقول السفهاء',
      startSurahNum: 2,
      startSurahName: 'البقرة',
      startAyah: 142,
      endSurahNum: 2,
      endSurahName: 'البقرة',
      endAyah: 252,
      versesCount: 111,
    ),
    JuzModel(
      number: 3,
      name: 'تلك الرسل',
      startSurahNum: 2,
      startSurahName: 'البقرة',
      startAyah: 253,
      endSurahNum: 3,
      endSurahName: 'آل عمران',
      endAyah: 92,
      versesCount: 126,
    ),
    JuzModel(
      number: 4,
      name: 'لن تنالوا البر',
      startSurahNum: 3,
      startSurahName: 'آل عمران',
      startAyah: 93,
      endSurahNum: 4,
      endSurahName: 'النساء',
      endAyah: 23,
      versesCount: 131,
    ),
    JuzModel(
      number: 5,
      name: 'والمحصنات',
      startSurahNum: 4,
      startSurahName: 'النساء',
      startAyah: 24,
      endSurahNum: 4,
      endSurahName: 'النساء',
      endAyah: 147,
      versesCount: 124,
    ),
    JuzModel(
      number: 6,
      name: 'لا يحب الله',
      startSurahNum: 4,
      startSurahName: 'النساء',
      startAyah: 148,
      endSurahNum: 5,
      endSurahName: 'المائدة',
      endAyah: 81,
      versesCount: 110,
    ),
    JuzModel(
      number: 7,
      name: 'وإذا سمعوا',
      startSurahNum: 5,
      startSurahName: 'المائدة',
      startAyah: 82,
      endSurahNum: 6,
      endSurahName: 'الأنعام',
      endAyah: 110,
      versesCount: 149,
    ),
    JuzModel(
      number: 8,
      name: 'ولو أننا',
      startSurahNum: 6,
      startSurahName: 'الأنعام',
      startAyah: 111,
      endSurahNum: 7,
      endSurahName: 'الأعراف',
      endAyah: 87,
      versesCount: 142,
    ),
    JuzModel(
      number: 9,
      name: 'قال الملأ',
      startSurahNum: 7,
      startSurahName: 'الأعراف',
      startAyah: 88,
      endSurahNum: 8,
      endSurahName: 'الأنفال',
      endAyah: 40,
      versesCount: 159,
    ),
    JuzModel(
      number: 10,
      name: 'واعلموا',
      startSurahNum: 8,
      startSurahName: 'الأنفال',
      startAyah: 41,
      endSurahNum: 9,
      endSurahName: 'التوبة',
      endAyah: 92,
      versesCount: 127,
    ),
    JuzModel(
      number: 11,
      name: 'يعتذرون',
      startSurahNum: 9,
      startSurahName: 'التوبة',
      startAyah: 93,
      endSurahNum: 11,
      endSurahName: 'هود',
      endAyah: 5,
      versesCount: 151,
    ),
    JuzModel(
      number: 12,
      name: 'وما من دابة',
      startSurahNum: 11,
      startSurahName: 'هود',
      startAyah: 6,
      endSurahNum: 12,
      endSurahName: 'يوسف',
      endAyah: 52,
      versesCount: 170,
    ),
    JuzModel(
      number: 13,
      name: 'وما أبرئ نفسي',
      startSurahNum: 12,
      startSurahName: 'يوسف',
      startAyah: 53,
      endSurahNum: 14,
      endSurahName: 'إبراهيم',
      endAyah: 52,
      versesCount: 154,
    ),
    JuzModel(
      number: 14,
      name: 'ربما',
      startSurahNum: 15,
      startSurahName: 'الحجر',
      startAyah: 1,
      endSurahNum: 16,
      endSurahName: 'النحل',
      endAyah: 128,
      versesCount: 227,
    ),
    JuzModel(
      number: 15,
      name: 'سبحان الذي',
      startSurahNum: 17,
      startSurahName: 'الإسراء',
      startAyah: 1,
      endSurahNum: 18,
      endSurahName: 'الكهف',
      endAyah: 74,
      versesCount: 185,
    ),
    JuzModel(
      number: 16,
      name: 'قال ألم أقل لك',
      startSurahNum: 18,
      startSurahName: 'الكهف',
      startAyah: 75,
      endSurahNum: 20,
      endSurahName: 'طه',
      endAyah: 135,
      versesCount: 269,
    ),
    JuzModel(
      number: 17,
      name: 'اقترب للناس',
      startSurahNum: 21,
      startSurahName: 'الأنبياء',
      startAyah: 1,
      endSurahNum: 22,
      endSurahName: 'الحج',
      endAyah: 78,
      versesCount: 190,
    ),
    JuzModel(
      number: 18,
      name: 'قد أفلح المؤمنون',
      startSurahNum: 23,
      startSurahName: 'المؤمنون',
      startAyah: 1,
      endSurahNum: 25,
      endSurahName: 'الفرقان',
      endAyah: 20,
      versesCount: 202,
    ),
    JuzModel(
      number: 19,
      name: 'وقال الذين لا يرجون',
      startSurahNum: 25,
      startSurahName: 'الفرقان',
      startAyah: 21,
      endSurahNum: 27,
      endSurahName: 'النمل',
      endAyah: 55,
      versesCount: 339,
    ),
    JuzModel(
      number: 20,
      name: 'أمن خلق',
      startSurahNum: 27,
      startSurahName: 'النمل',
      startAyah: 56,
      endSurahNum: 29,
      endSurahName: 'العنكبوت',
      endAyah: 45,
      versesCount: 171,
    ),
    JuzModel(
      number: 21,
      name: 'اتل ما أوحي',
      startSurahNum: 29,
      startSurahName: 'العنكبوت',
      startAyah: 46,
      endSurahNum: 33,
      endSurahName: 'الأحزاب',
      endAyah: 30,
      versesCount: 178,
    ),
    JuzModel(
      number: 22,
      name: 'ومن يقنت',
      startSurahNum: 33,
      startSurahName: 'الأحزاب',
      startAyah: 31,
      endSurahNum: 36,
      endSurahName: 'يس',
      endAyah: 27,
      versesCount: 169,
    ),
    JuzModel(
      number: 23,
      name: 'وما أنزلنا',
      startSurahNum: 36,
      startSurahName: 'يس',
      startAyah: 28,
      endSurahNum: 39,
      endSurahName: 'الزمر',
      endAyah: 31,
      versesCount: 357,
    ),
    JuzModel(
      number: 24,
      name: 'فمن أظلم',
      startSurahNum: 39,
      startSurahName: 'الزمر',
      startAyah: 32,
      endSurahNum: 41,
      endSurahName: 'فصلت',
      endAyah: 46,
      versesCount: 175,
    ),
    JuzModel(
      number: 25,
      name: 'إليه يرد علم الساعة',
      startSurahNum: 41,
      startSurahName: 'فصلت',
      startAyah: 47,
      endSurahNum: 45,
      endSurahName: 'الجاثية',
      endAyah: 37,
      versesCount: 246,
    ),
    JuzModel(
      number: 26,
      name: 'حم',
      startSurahNum: 46,
      startSurahName: 'الأحقاف',
      startAyah: 1,
      endSurahNum: 51,
      endSurahName: 'الذاريات',
      endAyah: 30,
      versesCount: 195,
    ),
    JuzModel(
      number: 27,
      name: 'قال فما خطبكم',
      startSurahNum: 51,
      startSurahName: 'الذاريات',
      startAyah: 31,
      endSurahNum: 57,
      endSurahName: 'الحديد',
      endAyah: 29,
      versesCount: 399,
    ),
    JuzModel(
      number: 28,
      name: 'قد سمع الله',
      startSurahNum: 58,
      startSurahName: 'المجادلة',
      startAyah: 1,
      endSurahNum: 66,
      endSurahName: 'التحريم',
      endAyah: 12,
      versesCount: 137,
    ),
    JuzModel(
      number: 29,
      name: 'تبارك الذي',
      startSurahNum: 67,
      startSurahName: 'الملك',
      startAyah: 1,
      endSurahNum: 77,
      endSurahName: 'المرسلات',
      endAyah: 50,
      versesCount: 431,
    ),
    JuzModel(
      number: 30,
      name: 'عم يتساءلون',
      startSurahNum: 78,
      startSurahName: 'النبأ',
      startAyah: 1,
      endSurahNum: 114,
      endSurahName: 'الناس',
      endAyah: 6,
      versesCount: 564,
    ),
  ];
}
